security:
  user:
    password: password

logging:
  level:
    #org.springframework.web: DEBUG
    #com.zaxxer.hikari.pool.HikariPool: DEBUG
    com.zaxxer.hikari.pool: DEBUG

#H2Console
spring:
  h2:
    console:
      enabled: true
      path: /admin/h2console

---

spring:
  profiles: dev
  # To disable thymeleaf caching, only for development
  thymeleaf:
    cache: false
  datasource:
    initialize: true
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql

---

spring:
  profiles: prod

  datasource:
    url: jdbc:h2:file:/tmp/kilim
    username: sa
    password:
    initialize: true
    schema: classpath:sql/schema.sql
    #data: classpath:sql/data.sql