security:
  user:
    password: password

logging:
  level:
    #org.springframework.web: DEBUG
    #com.zaxxer.hikari.pool.HikariPool: DEBUG
    com.zaxxer.hikari.pool: DEBUG

#H2Console
spring:
  h2:
    console:
      enabled: true
      path: /admin/h2console
  mail:
    host: localhost
    port: 2525
    protocol: smtp

kilim:
  xodusPath: /tmp/kilimData
  telegramToken: ****
  telegramGroupId: ****

---

spring:
  profiles: dev
  # To disable thymeleaf caching, only for development
  thymeleaf:
    cache: false
  datasource:
    initialize: true
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
  mail:
    host: smtp.gmail.com
    port: 587
    username: kilim.saas@gmail.com
    password: zipiri77
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

---

spring:
  profiles: prod

  datasource:
    url: jdbc:h2:file:/tmp/kilim
    username: sa
    password:
    initialize: true
    schema: classpath:sql/schema.sql
    #data: classpath:sql/data.sql